### ISSUE TITLE
Create a "select" mode

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/arcs#10]
This follows on from https://github.com/Michael-F-Bryan/arcs/issues/9#issuecomment-579095166:

> I would like to add to this another mode for *selecting* or *picking* already drawn geometry.
>
> This is probably the most used functionality and can probably also be implemented as a mode.
>
> As an algorithm for finding things under the mouse cursor we have the most important thing already, as we can do a quick sort of all `DrawingObjects` whose `BoundingBox` contains the `MousePosition` in `WorldSpace` and do some *fine-grained* checks afterwards

---

We need an interactive mode which lets us mark an object as selected and move them around the drawing by clicking and dragging.

This will necessitate a couple new concepts on top of #9:

- `Selected` component (see `specs::storage::NullStorage`)
- The `SelectMode` itself
- An efficient way to see what is under the cursor

**Comment by Michael-F-Bryan** [comment]
Regarding the lookup mechanism, I was thinking of creating a new `System` which will detects when an entity's `BoundingBox` has changed (kinda like [`arcs::systems::SyncBounds`][sync]) and use those change notifications to update a lookup data structure (e.g. [`QuadTree`][quad]). That way we have a really fast (approx `O(log n)`) way to find out which objects are within a certain area.

This data structure can also be used to make rendering easier by clipping objects that lie off screen.

[sync]: https://docs.rs/arcs/0.2.0/arcs/systems/struct.SyncBounds.html
[quad]: https://en.wikipedia.org/wiki/Quadtree

**Comment by DerLando** [comment]
I think I found a nice crate for this: https://crates.io/crates/quadtree_rs

I'm thinking of implementing this on top of the `Bounded` trait:

-  everything that can be *bounded* can be inserted in the quadtree
-  implement `Bounded` for `Window`, so we can query a region intersection between the screens viewport and all `DrawingObjects` in `World`

**Comment by Michael-F-Bryan** [comment]
Yeah... I'm not a massive fan of that API either. Something similar to [`ntree`](https://docs.rs/ntree/0.1.0/ntree/index.html) would work well, otherwise [`aabb_quadtree`](https://docs.rs/aabb-quadtree/) looks quite promising.

We need the ability to associate a `BoundingBox` with an `Entity` and then over time tell the `QuadTree` that our `Entity` has moved so it can re-balance its bookkeeping internally.  The vanilla `QuadTree` implementation just maps `BoundingBox -> Entity`, but to avoid checking every object in the tree we'd also need to maintain some `Entity -> BoundingBox` mapping. I think that's what `aabb_quadtree` is doing under the hood with `ItemId`.

I have a feeling in the long run we'll end up implementing our own `QuadTree` type so it can be tailored to `arcs`'s needs, but for now it'd be nice to reuse an existing implementation.

> Implement Bounded for Window, so we can query a region intersection between the screens viewport and all DrawingObjects in World

This gets problematic because you need to know the window dimensions in pixels. I don't think we currently do that, although it shouldn't be too hard to create a `WindowDimensions` component which is a newtype around `kurbo::Size`. We also need to make sure the WebAssembly demo listens to resize events so it can be kept in sync.

That said, we [do this already](https://github.com/Michael-F-Bryan/arcs/blob/a98061ef3e88c557e12cd0b158976d23c7aec75b/demo/src/lib.rs#L21) in an ad-hoc way. Turning it into a proper `Component` would just formalise things.

**Comment by DerLando** [comment]
I'll give `aabb_quadtree` a go for now, although it hasn't been updated in 8 months.

I agree that in the long run an arcs specific implementation would be nice, especially since the implementations I could find aren't too long (under 500 loc)

**Comment by DerLando** [comment]
I see some problems:

- `aabb_quadtree` is initialized with a fixed `boundingbox` which can never change, if you try to insert geometry outside of this bounds, [it fails:](https://github.com/TyOverby/aabb-quadtree/blob/5863b4b11811b967d9301021b441b90d78acb466/src/lib.rs#L180-L182)
- the `insert` and `query` methods both rely on `euclids` `TypedRect.contains()` method, `TypedRect` is deprecated so we would be version-locked to *0.19.8*.
- `TypeRect` has some questionable rules for when it [contains a point:](https://docs.rs/euclid/0.19.8/src/euclid/rect.rs.html#209)
  >    /// Returns true if this rectangle contains the point. Points are considered
    /// in the rectangle if they are on the left or top edge, but outside if they
    /// are on the right or bottom edge.

Other then that, it will work for now! I can submit a PR later where we can discuss further implementation details ;)
