### ISSUE TITLE
Reuse a standard geometry types instead of writing our own Vector

### ISSUE THREAD

**Issue by Michael-F-Bryan** [Michael-F-Bryan/arcs#11]
At the moment we're reimplementing a lot of basic geometry math with `Vector` and `BoundingBox`. Is it worth reusing primitive types from an existing geometry library?

**Comment by Michael-F-Bryan** [comment]
To get the ball rolling, I really like the way [`euclid`](https://docs.rs/euclid/0.20.7/euclid/index.html) attaches a tag to prevent accidentally mixing up coordinate spaces. 

At the moment we *kinda* do this by using `kurbo::Point` for *Canvas Space* (things drawn on a canvas) and *Drawing Space* (the coordinate space for all things in the "drawing").

Some other benefits are:

- It's a small library in terms of functionality and dependencies
- It doesn't try to be *too* generic (I'm looking at you [`ndarray::ArrayBase`](https://docs.rs/ndarray/0.13.0/ndarray/struct.ArrayBase.html)
- Part of the servo project
- It handles [`Angle`](https://docs.rs/euclid/0.20.7/euclid/struct.Angle.html)s and the associated modular arithmetic annoyances

**Comment by Michael-F-Bryan** [comment]
Some alternatives I've looked are [`cgmath`](https://docs.rs/cgmath) and [`ndarray`](https://docs.rs/ndarray). I'm leaning away from both because it feels like `cgmath` is aiming for a different audience, and I've already mentioned some of my gripes around `ndarray`/`nalgebra`.

**Comment by DerLando** [comment]
I mean the *description* of `euclid` sounds really promising:
> A collection of strongly typed math tools for computer graphics with an inclination towards 2d graphics and layout.

Out of all the crates named it's the only one I haven't used before, but sure looks really promising!

**Comment by Michael-F-Bryan** [comment]
I've already started a branch switching over to `euclid` locally and so far it looks quite promising... I just need to finish resolving the hundreds of compile errors then look over to make sure I haven't subtly broken anything.
